//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Sync
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySyncEntities : DbContext
    {
        public MySyncEntities()
            : base("name=MySyncEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FileFilter> FileFilter { get; set; }
        public DbSet<History> History { get; set; }
        public DbSet<ServerEntryPoint> ServerEntryPoint { get; set; }
        public DbSet<SynchronizationItem> SynchronizationItem { get; set; }
    }
}
