//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynchronizationItem
    {
        public long id { get; set; }
        public Nullable<decimal> serverEntryPointId { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public string extension { get; set; }
        public string creationTime { get; set; }
        public string lastAccessTime { get; set; }
        public string lastWriteTime { get; set; }
        public string lastSyncTime { get; set; }
        public Nullable<decimal> size { get; set; }
        public Nullable<decimal> folderFlag { get; set; }
        public Nullable<decimal> files { get; set; }
        public Nullable<decimal> folders { get; set; }
    }
}
