//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToSync
    {
        public long id { get; set; }
        public Nullable<decimal> synchronizationItemId { get; set; }
        public string syncType { get; set; }
    }
}
